@host=http://localhost:8080


PUT {{host}}/distanz/0/laufen

{
  "kilometers": 1.5
}

####
PUT {{host}}/distanz/1/laufen

{
  "kilometers": 1.4
}

####
GET {{host}}/distanz/0/laufen/all
####
GET {{host}}/distanz/1/laufen/all

#### Summe
GET {{host}}/distanz/0/laufen/sum

#### Summe
GET {{host}}/distanz/1/laufen/sum

