@host=http://127.0.0.1:8080


POST {{host}}/createuser

{
  "name": "asdfg",
  "pass": "qwertz"
}


### auth
POST {{host}}/authenticate

{
  "name": "asdffg",
  "pass": "qwertz"
}

#### put
PUT {{host}}/distanz/0/laufen
Authorization: Basic base64-user-password

{
  "kilometers": 1.5
}

####
PUT {{host}}/distanz/1/laufen

{
  "kilometers": 1.4
}

#### Highscore
PUT {{host}}/highscore
Authorization: Basic YXNkOmFzZA==

{
  "kilometers": 1.5
}

