name: Rust

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk wasm-bindgen-cli

      - name: Check Backend
        run: |
          cargo build -p jdav_server
          cargo test -p jdav_server

      - name: Build Frontend
        run: |
          cd jdav_client
          trunk build --release
